version: 2.1

executors:
  linux:
    docker:
      - image: cimg/python:3.10.5

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - run: echo hello

workflows:
  alphaCod3r:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              node-version: [10.0.0, 10.1.0, 10.2.0, 10.2.1, 10.3.0, 10.4.0, 10.4.1, 10.5.0, 10.6.0, 10.7.0]
